# Generated by Django 5.2.4 on 2025-07-18 09:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default=api.models.default_avatar, upload_to='profile_pics/'),
        ),
    ]
