# Generated by Django 5.2.4 on 2025-07-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_creator_alter_course_instructors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='submitted_for_approval',
        ),
        migrations.AddField(
            model_name='course',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='submission_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
