# Generated by Django 5.2.4 on 2025-07-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_submitted_for_approval_course_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('sandbox', 'Code Sandbox'), ('assignment', 'Assignment')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
