# Generated by Django 5.2.4 on 2025-07-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_activity_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
